name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Determine Image Tags
      id: tags
      run: |
        echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/adapter-bottom:latest,${{ secrets.DOCKERHUB_USERNAME }}/adapter-bottom:latest" >> $GITHUB_OUTPUT

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.tags.outputs.tags }}
        push: true
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/adapter-bottom:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/adapter-bottom:buildcache,mode=max